BaeYeongJu/ConsoleCalculatorTest

- ConsoleCalculator/ConsoleCalculator/Program.cs
간단하게 연산자 (+,-,/,%) 선택하여 계산하는 콘솔 계산기 기능 만듬.
> 간단한 연산자 콘솔 계산

- ConsoleCalculator/ConsoleCalculator/Program.cs
코드 줄이기 & 주석 추가 & 예외 처리 진행중
- 주석으로 해야 할 기능 추가
> 코드 줄이기 & 주석 추가 & 예외 처리 진행중

- ConsoleCalculator/ConsoleCalculator/Program.cs
> SetOperatorCalculate 함수 분리

- ConsoleCalculator/ConsoleCalculator.sln
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/TestProject1/TestProject1.csproj
- ConsoleCalculator/TestProject1/UnitTest1.cs
- 테스트 코드 추가 
- 간단하게 Add 함수 계산
- public 함수로 변경 & 계산하는 Add, Sub, Multiplication, Division, Remainder 함수들 내부에서 시작해서 내부로 끝나게 수정
- delegate를 사용해서 계산하는 함수의 값을 전달하게 변경할 예정
> 테스트 코드 추가 & 함수 내부로 사용하게 리팩토링

- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/TestProject1/UnitTest1.cs
> 테스트 코드 쪼개기

- ConsoleCalculator/TestProject1/UnitTest1.cs
테스트 코드에 Nunit 에 쓰이는 setup & teardown 와 같은 기능을 하는 [TestInitialize()] ,[TestCleanup()] 을 추가하였습니다.
그리고 테스트 코드를 줄였습니다.
참조)
https://stackoverflow.com/questions/6193744/what-would-be-an-alternate-to-teardown-and-setup-in-mstest
https://debugmode.net/2013/06/17/test-setup-and-teardown-in-unit-testing-using-nunit-part-2/
> 테스트 코드에 initialize & cleanup 메서드 추가

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/TestProject1/UnitTest.cs
Program 클래스에서 계산 기능 및 함수들 CalculateManager 라는 클래스로 분리함.
테스트 코드인 UnitTest에서 Initialize() 순서 앞으로 변경함.
테스트 코드로 실수 기능 할 예정
> 클래스 분리 및 테스트 코드 수정

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/TestProject1/UnitTest.cs
실수와 정수를 테스트 하기 위해 int 형 변수들을 double형으로 변경 및 정수 & 실수 테스트
메인 & 계산기 클래스의 int형 변수들을 double형으로 변경
> 실수&정수 테스트 코드 &변수들 실수형으로 변경

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/TestProject1/UnitTest.cs
연산자 테스트 코드 작성
IsNumberIntType함수 이름 변경 -> IsNumberDoubleType
> 연산자 테스트 코드 & 함수 이름 변경

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/TestProject1/UnitTest.cs
+/- 테스트 코드 추가 및 기능 구현
테스트 코드 symbol -> operator로 변경
> +/- 테스트 코드 추가 및 기능 구현

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/TestProject1/UnitTest.cs
PlusOrMinus에서 Negative로 이름 변경 & 기호 n으로 변경
> PlusOrMinus에서 Negative로 이름 변경 & 기호 n으로 변경

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/TestProject1/UnitTest.cs
> 연산자 . 테스트 코드 추가 및 기능 구현

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/TestProject1/UnitTest.cs
- 1/x 테스트 코드 추가 
- 1/x기능 추가 
- DecimalPoint로 이름 변경
> 1/x 테스트 코드 & 기능 추가

- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/ConsoleCalculator/UIManager.cs
- 결과 호출하는 부분 별도로 UIManager에 메서드로 생성
- main 프로그램에서 호출하는 부분 코드 줄임
> UIManager 추가

- ConsoleCalculator/TestProject1/UnitTest.cs
1/x 테스트 코드 수정함
-> Assert로 테스트가 아닌 로그만 확인을 함.
#17
> 1/x 테스트 코드 수정

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/ConsoleCalculator/UIManager.cs
- uiManager 관련 부분 제거 (UIManager 클래스에서)
- IsReciprocalOperator 코드 리팩토링 
- 결과 출력 하는 코드 부분 리팩토링 -> window 계산기의 출력문과 유사하게
> :recycle: refator: 결과 출력 & IsReciprocalOperator 메서드

- ConsoleCalculator/TestProject1/UnitTest.cs
- 테스트 코드 리팩토링 : DynamicData 사용 & 메서드 안에 여러 테스트 추가
- pow,sqart 테스트 코드 추가 (다음 pr에 함수 내용 추가)
> :recycle:  refator: 테스트 코드 리팩토링 & pow,sqart 테스트 코드 추가

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/ConsoleCalculator/UIManager.cs
-Pow & Sqart 기능을 추가함
-메인 코드 :불필요한 코드 제거
> :sparkles: feat: Pow & Sqart 기능 추가 (제곱근, 루트)

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/TestProject1/UnitTest.cs
> :recycle: refator: string으로 변환해줄려고 ToString 메소드 사용 부분 변경

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/TestProject1/UnitTest.cs
- 문자열 보간을 통해 수정 : Negative( ) & DecimalPoint( )
- 테스트 코드 리팩토링 : 값을 통해 간결하게 변경
- pow에서 SquareRoot2로 변경 (2제곱근)
> :recycle: refator:  ""으로 사용한 값들을 문자열 보간으로 간결하게 변경

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/ConsoleCalculator/UIManager.cs
- ConsoleCalculator/TestProject1/UnitTest.cs
- 기존 연산자 체크 함수 추가 & 계산시 잘못된 값은 NaN 처리
- 테스트 코드 추가 : 기존 연산자 값 맞는지 테스트 & enter 입력 키 확인 테스트
- ErrorMessage 간결화
- 메인 코드 : 코드 순서대로 읽을 수 있도록 변경
*NaN : 계산할 수 없는 값
https://learn.microsoft.com/ko-kr/dotnet/api/system.double.nan?view=net-7.0
NaN 오류 테스트 코드 작성 (테스트 케이스가 필요)
> :recycle: refactor: 읽기 쉬운 메인 코드 & 에러 메시지 부분 수정

- ConsoleCalculator/TestProject1/UnitTest.cs
- 테스트 코드 수정 :입력한 연산자 값이 같은지 비교 테스트 
-> 거짓인지 판단함
#30 에 이어서 수정
> :white_check_mark: test: InputOperatorEqualsTest 테스트 코드 수정 

- ConsoleCalculator/ConsoleCalculator/ConsoleCalculator.csproj
- ConsoleCalculator/TestProject1/TestProject1.csproj
- ConsoleCalculator/TestProject1/UnitTest.cs
- .net 5.0으로 변경
-테스트 코드 수정
양의 무한수라서 double.PositiveInfinity으로 변경
- c 테스트 코드 추가 : clear
> :white_check_mark: test: .net 5.0 으로 변경 & 테스트 코드 PositiveInfinity으로 변경

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/ConsoleCalculator/UIManager.cs
첫번째 숫자를 제거할 수 있는 Clear 기능 추가
추후에 키값 c를 누르면 전체 클리어 기능을 하게 할 예정.
> :hammer: feat: Clear 기능 추가

- ConsoleCalculator/ConsoleCalculator.sln
- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/ConsoleCalculator.csproj
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/ConsoleCalculator/UIManager.cs
- ConsoleCalculator/TestProject1/TestProject1.csproj
- ConsoleCalculator/TestProject1/UnitTest.cs
- ConsoleCalculator/TestProject1/UnitTest1.cs
> Develep merge

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/ConsoleCalculator/UIManager.cs
- 연산자 입력 대신에 Console 입력 키 값 추가
- ConsoleKey 값으로 대체 (string 대신)
> 연산자 입력 대신 콘솔 입력 키 추가 & ConsoleKey 값으로 대체

- ConsoleCalculator/TestProject1/UnitTest.cs
- 테스트 코드 수정
- ConsoleKey로 테스트 (string에서 enum인 ConsoleKey로 변경)
> :white_check_mark: test: 테스트 코드 수정 ConsoleKey로 대체

- ConsoleCalculator/ConsoleCalculator/CalculateManager.cs
- ConsoleCalculator/ConsoleCalculator/Program.cs
- ConsoleCalculator/ConsoleCalculator/UIManager.cs
- ConsoleKey 함수 UIManager로 옮김
- ConsoleKey 함수 정리
> :art: style: ConsoleKey 함수 UIManager로 이주
